### PR TITLE
Automatically add external link icon

### PR DESCRIPTION
**Pull request by josuebran**
### External Link

Add external icon automatically if href is different than docs.datastax.com
```
https://www.datastax.com[distinguish each paragraph,role=external,window=_blank]
https://www.datastax.com[distinguish each paragraph^]
https://www.datastax.com[distinguish each paragraph]
```
external-link

Use `remove-ext-icon` role to remove icon for external links
```
https://www.datastax.com[distinguish each paragraph,role=remove-ext-icon,window=_blank]
```

### CODE REVIEW

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Review by colegoldsmith — APPROVED** [review]
Looks good!

**Pull request merged**
