### PR TITLE
Use managed PAT for release builds [no-release]

### PR DESCRIPTION
**Pull request by mlr**

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Review by colegoldsmith — APPROVED** [review]
Nice!

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Pull request merged**
