### PR TITLE
DOC-4649: Adjust socials for developer-centric targets

### PR DESCRIPTION
**Pull request by msmygit**
See the request from Carter Rabasa here [in the slack channel](https://datastax.slack.com/archives/C173L75B9/p1726614461262979).

@kurtenj we need the social icon for Discord named `social-discord.svg` in the appropriate location like others to complete this PR. Where can we get such icons? TY

cc/ @kurtenj @aimurphy @eric-schneider @colegoldsmith

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by msmygit** [comment]
https://datastax.jira.com/browse/DOC-4649

**Comment by colegoldsmith** [comment]
@msmygit @kurtenj I committed an svg file that is sized properly and has the right fill color, and inverts color in dark mode. I sourced it from here https://discord.com/branding

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by crtr0** [comment]
The Github link should not have changed, please point to: https://github.com/datastax

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Review by crtr0 — APPROVED** [review]

**Review by colegoldsmith — APPROVED** [review]

**Pull request merged**
