### PR TITLE
New design tokens

### PR DESCRIPTION
**Pull request by colegoldsmith**
Screenshot 2024-11-06 at 12 08 56 PM

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> [18:08:58] Using gulpfile ~/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/gulpfile.js [18:08:58] Starting 'bundle'... [18:08:58] Starting 'clean'... [18:08:58] Finished 'clean' after 31 ms [18:08:58] Starting 'lint'... [18:08:59] Finished 'lint' after 1.38 s [18:08:59] Starting 'build'... Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme [18:09:04] gulp-imagemin: Minified 10 images (saved 73.6 kB - 49.2%) [18:09:07] 'build' errored after 8.1 s [18:09:07] [31mError[39m in plugin "[36mgulp-postcss[39m" Message: ENOENT: no such file or directory, stat '/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/src/css/typeface/~@fontsource/material-icons-outlined/files/material-icons-outlined-latin-400-normal.woff2' Details: errno: -2 code: ENOENT syscall: stat path: /home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/src/css/typeface/~@fontsource/material-icons-outlined/files/material-icons-outlined-latin-400-normal.woff2 fileName: /home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/src/css/site.css domainEmitter: [object Object] domainThrown: false Stack: Error: ENOENT: no such file or directory, stat '/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/src/css/typeface/~@fontsource/material-icons-outlined/files/material-icons-outlined-latin-400-normal.woff2' at Object.statSync (node:fs:1660:25) at Object.statSync (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/graceful-fs/polyfills.js:318:34) at getStatsSync (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/fs-extra/lib/util/stat.js:58:18) at Object.checkPathsSync (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/fs-extra/lib/util/stat.js:90:33) at Object.copySync (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38) at url (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/gulp.d/tasks/build.js:49:48) at /home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/postcss-url/src/type/custom.js:12:53 at async Promise.all (index 0) at async Promise.all (index 316) at async LazyResult.runAsync (/home/runner/work/datastax-docs-site/datastax-docs-site/ui-bundle-preview/node_modules/postcss/lib/lazy-result.js:261:11) [18:09:07] 'bundle' errored after 9.52 s

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Review by eric-schneider — APPROVED** [review]

**Pull request merged**
