### PR TITLE
Add Segment track calls to code copy button

### PR DESCRIPTION
**Pull request by colegoldsmith**
Adding Segment track calls to the copy button on code blocks

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by colegoldsmith** [comment]
This is a little hard to test because the draft build only builds the home docs repo, which doesn't have any code blocks. Also the draft build stopped working on the second run because it didn't rebuild the docs home pages, which are pointing at an old hash of the site.js file

**Comment by colegoldsmith** [comment]
Best way to test this I think is going to be with the PR to update the UI bundle version in the datastax-docs-site repo

**Review by eric-schneider — APPROVED** [review]

**Pull request merged**
