### PR TITLE
Auto scroll to current side nav item + show all breadcrumbs

### PR DESCRIPTION
**Pull request by colegoldsmith**

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Antora site build successful! :white_check_mark:
Deploying draft.

**Review by eric-schneider — APPROVED** [review]
Tested this with a local bundle and confirmed that the breadcrumbs and nav auto-scrolling are both behaving as expected 🎉

**Pull request merged**
