### PR TITLE
Icon macro update

### PR DESCRIPTION
**Pull request by colegoldsmith**
Adds some improvments in preparation for the updated icon macro in the datastax-docs-site repo

### CODE REVIEW

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build successful! :white_check_mark:
Deploying draft.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1731730346678,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1731730346679,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1731730346679,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1731730346679,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1731730346679,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2438ms.

**Review by eric-schneider — APPROVED** [review]

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732055468654,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732055468654,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732055468654,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732055468654,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732055468655,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2405ms.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732141463644,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732141463644,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732141463645,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732141463645,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732141463645,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2483ms.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732160476196,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732160476197,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732160476197,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732160476197,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732160476197,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2481ms.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732251523131,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732251523132,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732251523133,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732251523133,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732251523133,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2400ms.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732310427052,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732310427053,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732310427053,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732310427053,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732310427053,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2461ms.

**Comment by plpesvc-ds** [comment]
Build failure! :x:
> {"level":"error","time":1732573053556,"name":"asciidoctor:svg-macro","target":"database","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: database"} {"level":"error","time":1732573053557,"name":"asciidoctor:svg-macro","target":"diameter","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: diameter"} {"level":"error","time":1732573053557,"name":"asciidoctor:svg-macro","target":"orbit","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: orbit"} {"level":"error","time":1732573053558,"name":"asciidoctor:svg-macro","target":"circle-gauge","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: circle-gauge"} {"level":"error","time":1732573053558,"name":"asciidoctor:svg-macro","target":"wind","file":{"path":"modules/ROOT/pages/index.adoc"},"msg":"target of svg not found: wind"} > tailwindcss > tailwindcss build -c ${npm_config_tailwind_config_path} -i ${npm_config_css_path} -o ${npm_config_css_path} --minify Browserslist: caniuse-lite is outdated. Please run: npx update-browserslist-db@latest Why you should do it regularly: https://github.com/browserslist/update-db#readme Rebuilding... Done in 2460ms.

**Pull request merged**
