### PR TITLE
page survey and segment analytics

### PR DESCRIPTION
**Pull request by josuebran**
### Segment analytics

Usage
```
site:
  keys:
     segment: segment_key
```
Segment will capture elements with `a[data-track]` , `[data-track]:not(a)` attributes 

### Page survey

- Survey handlebar
- Yes/No survey buttons
- Feedback modal
- Added survey handlebar to tutorial layout
- Requires segment key 

Yes/No buttons are captured by Segment `analytics.track` with `[data-survey]` attribute
Feedback modal form is captured by Segment `analytics.trackForm`

datastax-dialog

### Layouts
- Use handlebars for custom layouts
- Move admonition block styles to ds-blocks.css

### CODE REVIEW

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Review by colegoldsmith — APPROVED** [review]
Apologies for the delay in reviewing, this looks great!

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Pull request merged**
