### PR TITLE
Collapse nav sections

### PR DESCRIPTION
**Pull request by colegoldsmith**

### CODE REVIEW

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by colegoldsmith** [comment]
@eric-schneider I fixed the bottom nav items, they are position: sticky now so they stay floating at the bottom

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Pull request merged**
