### PR TITLE
update anchor header styles

### PR DESCRIPTION
**Pull request by josuebran**
- Move the anchor (which appears on hover) icon from left of the titles to the right
- Update layout styles for readability

### CODE REVIEW

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Review by colegoldsmith — CHANGES_REQUESTED** [review]
@josuebran Looks like this is messing with the "step" class. Screenshot here 
Screenshot 2023-11-02 at 3 40 15 PM

I had some success changing these styles in doc.css
```
.doc .step h2::before,    //<-- use ::after
.doc .step h3::before,    //<-- use ::after
.doc .step h4::before {   //<-- use ::after
  counter-increment: step;
  content: counter(step) ". ";
}

.doc .step h2 .anchor,  <-- delete all this, we don't need the margin anymore with your changes
.doc .step h3 .anchor,
.doc .step h4 .anchor {
  margin-left: -4.25ex;
}
```

**Comment by mlr** [comment]
UI bundle preview build successful! :white_check_mark:
Deploying preview to GitHub Pages.

**Comment by mlr** [comment]
Antora site build successful! :white_check_mark:
Deploying draft to GitHub Pages.

**Review by colegoldsmith — APPROVED** [review]
Looks good!

**Pull request merged**
